version: 2
updates:
  - package-ecosystem: "rust"
    directory: "/"
    schedule:
      # infrequent updates as this is a library: security updates shouldn't need
      # a major version bump, and minor versions can be controlled by users
      # Cargo.lock as they will be compatible.
      interval: "monthly"
